"""add api_keys table for script/machine authentication

Revision ID: 85a4f77176f3
Revises: 005
Create Date: 2026-08-04 21:11:43.416004
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '85a4f77176f3'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_repos_worker_uuid'), 'repos', ['worker_uuid'], unique=False)
    op.drop_constraint(op.f('uq_worker_registry_worker_id'), 'worker_registry', type_='unique')
    op.create_index(op.f('ix_worker_registry_worker_id'), 'worker_registry', ['worker_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_registry_worker_id'), table_name='worker_registry')
    op.create_unique_constraint(op.f('uq_worker_registry_worker_id'), 'worker_registry', ['worker_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_repos_worker_uuid'), table_name='repos')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
